import React, {Component, Fragment} from 'react';

export default class AboutGame extends Component {
  render () {
    return (
      <Fragment>
        <h2>About Game</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet nulla facilisi morbi tempus iaculis. Mi proin sed libero enim sed faucibus turpis. Pellentesque sit amet porttitor eget. Proin nibh nisl condimentum id venenatis. Habitant morbi tristique senectus et netus et. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Vitae congue eu consequat ac felis donec. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Purus sit amet volutpat consequat. Volutpat maecenas volutpat blandit aliquam etiam erat velit. At erat pellentesque adipiscing commodo elit at imperdiet. Accumsan in nisl nisi scelerisque eu.

Arcu odio ut sem nulla pharetra diam. Lacus suspendisse faucibus interdum posuere lorem. Eu facilisis sed odio morbi quis. Ultrices sagittis orci a scelerisque purus semper. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Dictum sit amet justo donec enim diam vulputate. Fusce ut placerat orci nulla. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Lectus nulla at volutpat diam ut venenatis tellus. Integer enim neque volutpat ac. Nec feugiat nisl pretium fusce id velit. Pellentesque dignissim enim sit amet venenatis urna. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.

Nunc sed velit dignissim sodales ut eu sem. Enim blandit volutpat maecenas volutpat. Luctus venenatis lectus magna fringilla. Bibendum ut tristique et egestas quis. Pellentesque elit eget gravida cum sociis. Blandit libero volutpat sed cras ornare. Egestas erat imperdiet sed euismod nisi. Urna id volutpat lacus laoreet non curabitur. Quam pellentesque nec nam aliquam sem. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Vulputate ut pharetra sit amet aliquam id. Massa ultricies mi quis hendrerit dolor magna. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Sodales neque sodales ut etiam sit amet nisl purus. Interdum posuere lorem ipsum dolor. Pretium nibh ipsum consequat nisl vel pretium lectus quam. In dictum non consectetur a erat nam.

A diam sollicitudin tempor id eu nisl. Pretium viverra suspendisse potenti nullam. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. A pellentesque sit amet porttitor eget dolor. Tempor orci dapibus ultrices in iaculis nunc sed. Justo donec enim diam vulputate. Diam volutpat commodo sed egestas egestas fringilla phasellus. Faucibus vitae aliquet nec ullamcorper sit amet. Libero nunc consequat interdum varius sit. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin.

Adipiscing tristique risus nec feugiat in fermentum. Nunc vel risus commodo viverra maecenas. Eu nisl nunc mi ipsum faucibus vitae. Vitae congue eu consequat ac felis donec. Turpis massa sed elementum tempus egestas sed sed risus. Vulputate ut pharetra sit amet aliquam. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Iaculis nunc sed augue lacus viverra vitae congue eu. Eros donec ac odio tempor orci dapibus. Vitae proin sagittis nisl rhoncus. Eget dolor morbi non arcu risus quis varius. Quam nulla porttitor massa id. Nibh sit amet commodo nulla facilisi nullam. Massa eget egestas purus viverra accumsan. Ullamcorper eget nulla facilisi etiam dignissim. Turpis egestas integer eget aliquet nibh praesent tristique. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Vel risus commodo viverra maecenas accumsan. Aliquet lectus proin nibh nisl condimentum id venenatis a. Ut porttitor leo a diam sollicitudin tempor id eu nisl.

Scelerisque varius morbi enim nunc faucibus a pellentesque. Quisque egestas diam in arcu cursus euismod. Orci a scelerisque purus semper eget. Urna porttitor rhoncus dolor purus non enim praesent elementum. Vestibulum lorem sed risus ultricies tristique. Consectetur lorem donec massa sapien faucibus et. Tortor pretium viverra suspendisse potenti nullam ac tortor. Eget duis at tellus at urna condimentum. Dignissim diam quis enim lobortis scelerisque. Risus nec feugiat in fermentum posuere urna. Fermentum posuere urna nec tincidunt praesent semper feugiat. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae.</p>
      </Fragment>
    );
  }
};